# Generated by Django 5.0.6 on 2024-06-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_comments_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_on', 'comment')},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Assitant', 'Assistant'), ('Patient', 'Patient')], default='Patient', max_length=50),
        ),
    ]
