# Generated by Django 5.0.6 on 2024-07-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_customuser_profile_pic_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Assitant', 'Assistant'), ('Doctor', 'Doctor')], default='Patient', max_length=50),
        ),
    ]
