# Generated by Django 5.0.6 on 2024-07-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospital', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, default='', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Assitant', 'Assistant'), ('Patient', 'Patient')], default='Patient', max_length=50),
        ),
    ]
