# Generated by Django 5.0.6 on 2024-07-22 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_customuser_groups_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Assitant', 'Assistant')], default='Patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.CharField(choices=[('is_available', 'is_available'), ('not_available', 'not_available'), ('sun-fri', 'sun-fri'), ('wed-thurs', 'wed-thurs'), ('sat', 'sat')], max_length=50),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('Comp Off', 'Compensation'), ('CL', 'Casual Leave'), ('ML', 'Medical Leave')], max_length=50)),
                ('leave_choice', models.CharField(choices=[('Full Day', 'Full Day Leave'), ('Second Half', 'Second Half Only'), ('First Half', 'First Half Only')], default='Full Day', max_length=50)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('no_of_leave', models.IntegerField(default=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
